---
-- Megami Tensei Wiki
-- page=Module:Gamedata
--
-- Licensed under CC BY-SA 3.0
--


local games = {
	['mt1'] = {
		colorb = '#f00',
		colorbg = '#000',
		font = '#f00',
		name = 'Megami Tensei',
	},
	['mt2'] = {
		colorb = '#c0b37c',
		colorbg = '#c0b37c',
		font = '#000',
		name = 'Megami Tensei II',
	},
	['kmt'] = {
		name = 'Kyūyaku Megami Tensei',
		fallback = 'mt1',
	},
	['kmt1'] = {
		name = 'Megami Tensei',
		fallback = 'mt1',
	},
	['kmt2'] = {
		name = 'Megami Tensei II',
		fallback = 'mt2',
	},
	['giten'] = {
		colorb = '#46304c',
		colorbg = '#46304c',
		font = '#ff3621',
		name = 'Giten Megami Tensei: Tokyo Mokushiroku',
	},
	['gmt'] = {
		fallback = 'giten',
	},
	['smt1'] = {
		colorb = '#608341',
		colorbg = '#608341',
		font = '#fff',
		font2 = '#529488',
		statt = '#529488',
		name = 'Shin Megami Tensei',
	},
	['smt2'] = {
		colorb = '#2F4F4F',
		colorbg = '#2F4F4F',
		font = '#fff',
		font2 = '#529488',
		statt = '#ffffff',
		statb = '#930906',
		name = 'Shin Megami Tensei II',
	},
	['smtif'] = {
		colorb = '#8FBC8F',
		colorbg = '#8FBC8F',
		font = '#000',
		font2 = '#529488',
		statt = '#529488',
		statb = '#de2805',
		name = 'Shin Megami Tensei: if...',
	},
	['smtifhc'] = {
		name = "Shin Megami Tensei: if... Hazama's Chapter",
		fallback = 'smtif',
	},
	['20xx'] = {
		colorb = '#c00',
		colorbg = '#c00',
		font = '#fff',
		name = 'Shin Megami Tensei: 20XX',
	},
	['20xxdc'] = {
		name = "Shin Megami Tensei: 20XX Devil's Colosseum",
		fallback = '20xx',
	},
	['smt3'] = {
		colorb = '#333158',
		colorbg = 'linear-gradient(90deg, #3b3a62, #201e33)',
		colorbg2 = 'linear-gradient(#3b3a62, #201e33)',
		font = '#fff',
		font2 = '#529488',
		hp = '#cb91ba',
		mp = '#a09dea',
		hp2 = '#f19246',
		mp2 = '#7b55e9',
		statt = '#529488',
		statb = '#b15a60', -- Demons
		statb2 = '#9beffb', -- Magatamas
		name = 'Shin Megami Tensei III: Nocturne',
	},
	['smtsj'] = {
		colorb = '#200470',
		colorbg = '#200470',
		font = '#fff',
		font2 = '#529488',
		hp = '#e39a94',
		mp = '#85e795',
		hp2 = '#ddbf77',
		mp2 = '#85bd64',
		statt = '#fff',
		statb = '#63c6b9',
		name = 'Shin Megami Tensei: Strange Journey',
	},
	['smt4'] = {
		colorb = '#fff',
		colorbg = '#fff',
		colorbg2 = '#F49800',
		font = '#000',
		font2 = '#F49800',
		hp = '#FDEC3C',
		mp = '#69BB29',
		statt = '#F49800',
		statb = '#8bc800',
		name = 'Shin Megami Tensei IV',
	},
	['smt4a'] = {
		colorb = '#fff',
		colorbg = '#fff',
		colorbg2 = '#394d5b',
		font = '#000',
		font2 = '#b0d6d7',
		hp = '#dcaa63',
		mp = '#499dc2',
		statt = '#a1ccd3', -- stat text
		statb = '#357c95',
		name = 'Shin Megami Tensei IV Apocalypse',
	},
	['smt4f'] = {
		fallback = 'smt4a',
	},
	['smt5'] = {
		colorb = '#bca750',
		colorbg = '#bca750',
		colorbg2 = '#847f61',
		font = '#FFF',
		font2 = '#F0E68C',
		hp = '#ADFF2F',
		mp = '#FFD700',
		statt = '#FAEBD7', -- stat text
		statb = '#FFFFFF',
		name = 'Shin Megami Tensei V',
	},
	['smtv'] = {
		fallback = 'smt5',
	},
	['smtim'] = {
		colorb = '#009d96',
		colorbg = '#009d96',
		font = '#fff',
		name = 'Shin Megami Tensei IMAGINE',
	},
	['smt9'] = {
		colorb = '#0c103e',
		colorbg = '#0c103e',
		font = '#c0c0c0',
		statt = '#ffffff',
		statb = '#ffff00',
		name = 'Shin Megami Tensei NINE',
	},
	['ldx2'] = {
		colorb = '#8A448A',
		colorbg = '#8A448A',
		font = '#FFF',
		hp = '#e39a94',
		mp = '#85e795',
		name = 'Shin Megami Tensei: Liberation Dx2',
	},
	['lb1'] = {
		colorb = '#f00',
		colorbg = '#f00',
		font = '#fff',
		name = 'Last Bible',
	},
	['lb2'] = {
		colorb = '#f04',
		colorbg = '#f04',
		font = '#fff',
		name = 'Last Bible II',
	},
	['lb3'] = {
		colorb = '#959',
		colorbg = '#959',
		font = '#fff',
		name = 'Last Bible III',
	},
	['ab'] = {
		colorb = '#f40',
		colorbg = '#f40',
		font = '#fff',
		name = 'Another Bible',
	},
	['lbs'] = {
		colorb = '#658',
		colorbg = '#658',
		font = '#fff',
		name = 'Last Bible Special',
	},
	['majin1'] = {
		colorb = '#002446',
		colorbg = '#002446',
		font = '#fff',
		name = 'Majin Tensei',
	},
	['majin2'] = {
		colorb = '#514F7E',
		colorbg = '#514F7E',
		font = '#fff',
		name = 'Majin Tensei II: Spiral Nemesis',
	},
	['ronde'] = {
		colorb = '#bb1442',
		colorbg = '0d0d0d',
		font = '#bb1442',
		name = 'Ronde',
	},
	['smtds'] = {
		colorb = '#4372AA',
		colorbg = '#4372AA',
		font = '#fff',
		name = 'Shin Megami Tensei: Devil Summoner',
	},
	['sh'] = {
		colorb = '#302878',
		colorbg = '#302878',
		font = '#fff',
		name = 'Devil Summoner: Soul Hackers',
	},
	['sh2'] = {
		colorb = '#ADFF2F',
		colorbg = '#F587FD',
		colorbg2 = '#EED4D9',
		font = '#000',
		font2 = '#9F99AA',
		hp = '#00FFFF',
		mp = '#FFFF00',
		statt = '#9F99AA',
		statb = '#9d91e7',
		name = 'Soul Hackers 2',
	},
	['raidou1'] = {
		colorb = '#856363',
		colorbg = '#856363',
		font = '#000',
		name = 'Devil Summoner: Raidou Kuzunoha vs. The Soulless Army',
	},
	['raidou2'] = {
		colorb = '#8e283d',
		colorbg = '#8e283d',
		font = '#fff',
		name = 'Devil Summoner: Raidou Kuzunoha vs. King Abaddon',
	},
	['dcbrb'] = {
		colorb = '#dcb',
		colorbg = '#dcb',
		font = '#000',
		name = 'Devil Children Black/Red Book',
		name1 = 'Devil Children Black Book',
		name2 = 'Devil Children Red Book',
	},
	['dcbrp'] = {
		colorb = '#dcb',
		colorbg = '#dcb',
		font = '#000',
		name = 'Devil Children Black/Red Book',
		name2 = 'Devil Children PS',
		fallback = 'dcbrb',
	},
	['dcwb'] = {
		colorb = '#dcb',
		colorbg = '#dcb',
		font = '#000',
		name = 'Devil Children White Book',
		fallback = 'dcbrb',
	},
	['childred'] = {
		colorb = '#c00',
		colorbg = '#c00',
		font = '#000',
		name = 'Devil Children Red/Black Book',
		name1 = 'Devil Children Red Book',
		name2 = 'Devil Children Black Book',
	},
	['childblack'] = {
		colorb = '#c00',
		colorbg = '#c00',
		font = '#000',
		name = 'Devil Children Red/Black Book',
		fallback = 'childred',
	},
	['childps'] = {
		colorb = '#c93',
		colorbg = '#c93',
		font = '#000',
		name = 'Devil Children Red/Black Book',
		name2 = 'Devil Children PS',
	},
	['childwhite'] = {
		colorb = '#fff',
		colorbg = '#fff',
		font = '#000',
		name = 'Devil Children White Book',
	},
	['childlight'] = {
		colorb = '#60c',
		colorbg = '#60c',
		font = '#fff',
		name = 'DemiKids Light/Dark Version',
		name1 = 'DemiKids Light Version',
		name2 = 'DemiKids Dark Version',
		name3 = 'DemiKids',
	},
	['childdark'] = {
		fallback = 'childlight',
	},
	['dm'] = {
		fallback = 'childlight',
	},
	['dmk'] = {
		fallback = 'childlight',
	},
	['childfire'] = {
		colorb = '#f93',
		colorbg = '#f93',
		font = '#000',
		name = 'Devil Children Fire/Ice Book',
		name1 = 'Devil Children Fire Book',
		name2 = 'Devil Children Ice Book',
	},
	['childice'] = {
		colorb = '#f93',
		colorbg = '#f93',
		font = '#000',
		name = 'Devil Children Fire/Ice Book',
		fallback = 'childfire',
	},
	['childmessiah'] = {
		colorb = '#c30',
		colorbg = '#c30',
		font = '#000',
		name = 'Devil Children Messiah Riser',
		name2 = 'Messiah Riser',
	},
	['p1'] = {
		colorb = '#A9A9A9',
		colorbg = '#A9A9A9',
		font = '#000',
		statt = '#9098af',
		statb = '#bc023b',
		name = 'Persona',
	},
	['p2is'] = {
		colorb = '#8B668B',
		colorbg = '#8B668B',
		font = '#fff',
		statt = '#b490b4',
		statb = '#8B668B',
		name = 'Persona 2: Innocent Sin',
	},
	['p2ep'] = {
		colorb = '#B3668B',
		colorbg = '#B3668B',
		font = '#fff',
		statt = '#d4a1ba',
		statb = '#B3668B',
		name = 'Persona 2: Eternal Punishment',
	},
	['p3'] = {
		colorb = '#4372AA',
		colorbg = '#4372AA',
		font = '#000',
		hp2 = '#f19246',
		mp2 = '#7b55e9',
		statt = '#82bfec',
		statb = '#79aaf6',
		name = 'Persona 3',
	},
	['p3f'] = {
		name = 'Persona 3 FES',
		fallback = 'p3',
	},
	['p3p'] = {
		name = 'Persona 3 Portable',
		fallback = 'p3',
	},
	['p3ta'] = {
		name = 'The Answer',
		fallback = 'p3',
	},
	['p3d'] = {
		name = 'Persona 3: Dancing in Moonlight',
		fallback = 'p3',
	},
	['p3re'] = {
		name = 'Persona 3 Reload',
		colorb = '#4372AA',
		colorbg = '#4372AA',
		font = '#000',
		hp2 = '#f19246',
		mp2 = '#7b55e9',
		statt = '#82bfec',
		statb = '#79aaf6',
	},
	['pts'] = {
		colorb = '#26466D',
		colorbg = '#26466D',
		font = '#fff',
		name = 'Persona -trinity soul-',
	},
	['p4'] = {
		colorb = '#FFE600',
		colorbg = '#FFE600',
		font = '#000',
		hp2 = '#eef243',
		mp2 = '#acfa35',
		statt = '#ffdf2d',
		statb = '#ffff85',
		name = 'Persona 4',
	},
	['p4g'] = {
		name = 'Persona 4 Golden',
		fallback = 'p4',
	},
	['p4a'] = {
		name = 'Persona 4 Arena',
		fallback = 'p4',
	},
	['p4au'] = {
		name = 'Persona 4 Arena Ultimax',
		fallback = 'p4',
	},
	['p4d'] = {
		name = 'Persona 4: Dancing All Night',
		fallback = 'p4',
	},
	['pq'] = {
		colorb = '#AA1CA9',
		colorbg = '#AA1CA9',
		font = '#000',
		statb = '#ded8aa',
		name = 'Persona Q',
		name2 = 'Persona Q: Shadow of the Labyrinth',
	},
	['pq2'] = {
		colorb = '#FF520C',
		colorbg = '#FF520C',
		font = '#fff',
		statb = '#ded8aa',
		name = 'Persona Q2',
		name2 = 'Persona Q2: New Cinema Labyrinth',
	},
	['p5'] = {
		colorb = '#f41000',
		colorbg = '#f41000',
		colorbg2 = '#000',
		font = '#fff',
		font2 = '#fafa5b',
		hp = '#65ffdd',
		mp = '#ff73f0',
		hp2 = '#65ffdd',
		mp2 = '#ff73f0',
		statt = '#f9a804', -- stat text/not stat figure
		statb = '#f41000',
		name = 'Persona 5',
	},
	['p5r'] = {
		colorb = '#f41000',
		colorbg = '#f41000',
		colorbg2 = '#000',
		font = '#fff',
		font2 = '#fafa5b',
		hp = '#65ffdd',
		mp = '#ff73f0',
		hp2 = '#65ffdd',
		mp2 = '#ff73f0',
		statt = '#f9a804', -- stat text/not stat figure
		statb = '#f41000',
		name = 'Persona 5 Royal',
	},
	['p5s'] = {
		colorb = '#f41000',
		colorbg = '#f41000',
		colorbg2 = '#000',
		font = '#fff',
		font2 = '#fafa5b',
		hp = '#65ffdd',
		mp = '#ff73f0',
		hp2 = '#65ffdd',
		mp2 = '#ff73f0',
		statt = '#f9a804', -- stat text/not stat figure
		statb = '#f41000',
		name = 'Persona 5 Strikers',
	},
	['p5d'] = {
		name = 'Persona 5: Dancing in Starlight',
		fallback = 'p5',
	},
	['cs'] = {
		colorb = '#0047AB',
		colorbg = '#0047AB',
		font = '#fff',
		name = 'Shin Megami Tensei Trading Card: Card Summoner',
		name2 = 'Card Summoner',
	},
	['ddsaga1'] = {
		colorb = '#66CD00',
		colorbg = '#66CD00',
		font = '#000',
		name = 'Digital Devil Saga: Avatar Tuner',
	},
	['ddsaga2'] = {
		colorb = '#EC8A05',
		colorbg = '#EC8A05',
		font = '#000',
		name = 'Digital Devil Saga: Avatar Tuner 2',
	},
	['desu1'] = {
		colorb = '#e83145',
		colorbg = '#e83145',
		font = '#fff',
		hp = '#cb91ba',
		mp = '#a09dea',
		hp2 = '#f19246',
		mp2 = '#7b55e9',
		statt = '#fff',
		statb = '#206880',
		name = 'Devil Survivor',
	},
	['desu1oc'] = {
		name = 'Devil Survivor Overclocked',
		fallback = 'desu1',
	},
	['desu2'] = {
		colorb = '#0078e8',
		colorbg = '#0078e8',
		font = '#fff',
		hp = '#cb91ba',
		mp = '#a09dea',
		hp2 = '#f19246',
		mp2 = '#7b55e9',
		statt = '#fff',
		statb = '#206880',
		name = 'Devil Survivor 2',
	},
	['desu2rb'] = {
		name = 'Devil Survivor 2 Record Breaker',
		fallback = 'desu2',
	},
	['mx'] = {
		colorb = '#f00',
		colorbg = '#fff',
		font = '#000',
		name = 'Maken X',
	},
	['tmsfe'] = {
		colorb = '#84FF00',
		colorbg = '#84FF00',
		font = '#000',
		name = 'Tokyo Mirage Sessions ♯FE',
		name2 = 'Genei Ibunroku#FE',
	},
	['smtxfe'] = {
		name = 'Shin Megami Tensei x Fire Emblem',
		fallback = 'tmsfe',
	},
	[''] = {
		colorb = '#000',
		colorbg = '#000',
		font = '#fff',
		name = '',
	},
	['dx2'] = {
		name = 'Shin Megami Tensei: Liberation Dx2',
		colorb = '#9ee1db',
		colorbg = '#9ee1db',
		colorbg2 = '#000',
		font = '#fff',
	},
}

return {
	games = games,
}


-- [[Category:Modules]]
